# Generated by Django 2.2.6 on 2019-12-03 10:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OptionRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uah_purchase', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Purchase rate of ukrainian hryvnia')),
                ('uah_sale', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Sale rate of ukrainian hryvnia')),
                ('usd', models.IntegerField(default=1, verbose_name='Number of dollar units')),
                ('date_of_rate', models.DateField(verbose_name='Date of rate')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date of creation')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Option rate of currency(purchase and sale)',
            },
        ),
        migrations.CreateModel(
            name='MainRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uah', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Rate of ukrainian hryvnia')),
                ('usd', models.IntegerField(default=1, verbose_name='Number of dollar units')),
                ('date_of_rate', models.DateField(verbose_name='Date of rate')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date of creation')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Main rate of currency',
            },
        ),
    ]
