# Generated by Django 2.2.6 on 2019-12-03 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('currency_exchange', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mainrate',
            name='author',
        ),
        migrations.RemoveField(
            model_name='optionrate',
            name='author',
        ),
    ]
